### ISSUE TITLE
Separate goldfish entries

### ISSUE THREAD

**Issue by yungwilder** [jonathanfeng/new_horizons#8]
I assume the three goldfish types are consolidated into the singular 'goldfish' entry, but I would appreciate having them displayed separately for cross referencing against the in game book.

**Comment by VitamintK** [comment]
From what I see, all three goldfish have separate entries already.  I'm guessing this is related to #5 (the page only shows the fish currently spawning in your timezone, so if you view the page outside the active hours of the other two goldfish, their entries won't show up.)

**Comment by yungwilder** [comment]
That seems to be correct. Ty for this. Closing
